
/*
 * 
 */

package com.experian.payline.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.0
 * Fri Jan 07 11:58:06 CET 2011
 * Generated source version: 2.3.0
 * 
 */


@WebServiceClient(name = "WebPaymentAPI", 
                  wsdlLocation = "http://www.payline.com/wsdl/v4_0/homologation/WebPaymentAPI.wsdl",
                  targetNamespace = "http://impl.ws.payline.experian.com") 
public class WebPaymentAPI_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.ws.payline.experian.com", "WebPaymentAPI");
    public final static QName WebPaymentAPI = new QName("http://impl.ws.payline.experian.com", "WebPaymentAPI");
    static {
        URL url = null;
        try {
            url = new URL("http://www.payline.com/wsdl/v4_0/homologation/WebPaymentAPI.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://www.payline.com/wsdl/v4_0/homologation/WebPaymentAPI.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WebPaymentAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebPaymentAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebPaymentAPI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns WebPaymentAPI
     */
    @WebEndpoint(name = "WebPaymentAPI")
    public WebPaymentAPI getWebPaymentAPI() {
        return super.getPort(WebPaymentAPI, WebPaymentAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebPaymentAPI
     */
    @WebEndpoint(name = "WebPaymentAPI")
    public WebPaymentAPI getWebPaymentAPI(WebServiceFeature... features) {
        return super.getPort(WebPaymentAPI, WebPaymentAPI.class, features);
    }

}
