#!/bin/bash

TEMP_SVG="/tmp/button_temp.svg"

OUTPUT_DIR_PREFIX="../www_src/resources/"
MAX_WIDTH=158

generateButtons () { 
    
    base=$1
    lenght=$2
    height=$3
    type=$4
    svg_from=$5
    

    for i in 0 10 20 30 40 50 60 70 80 90 ; do
        w=$((158 * $i / 100)) 
        TARGET_PATH="m $svg_from $w,0 0,64.77822 -$w,0 c -2.88064,0 -5.19971,-2.31906 -5.19971,-5.1997 l 0,-16.72616 -11.56138,-10.46325 11.56138,-10.46325 0,-16.72616 c 0,-2.88064 2.31907,-5.1997 5.19971,-5.1997 z"
        xmlstarlet ed  -N "svg=http://www.w3.org/2000/svg" -u "//svg:svg/svg:g/svg:path[@id='progress']/@d" -v "$TARGET_PATH" $base > $TEMP_SVG
        

        inkscape -e $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_$i.png" -C -h $height $TEMP_SVG
        optipng $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_$i.png"
    done

    xmlstarlet ed  -N "svg=http://www.w3.org/2000/svg" -d "//svg:svg/svg:g/svg:path[@id='progress']" $base > $TEMP_SVG
    inkscape -e $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_empty.png" -C -h $height $TEMP_SVG
    optipng $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_empty.png"

    TARGET_PATH="m $svg_from  149.04109,0 c 2.88064,0 5.19971,2.31906 5.19971,5.1997 l 0,54.37882 c 0,2.88064 -2.31907,5.1997 -5.19971,5.1997 l -149.04109,0 c -2.88064,0 -5.19971,-2.31906 -5.19971,-5.1997 l 0,-16.72616 -11.56138,-10.46325 11.56138,-10.46325 0,-16.72616 c 0,-2.88064 2.31907,-5.1997 5.19971,-5.1997 z"
    xmlstarlet ed  -N "svg=http://www.w3.org/2000/svg" -u "//svg:svg/svg:g/svg:path[@id='progress']/@d" -v "$TARGET_PATH" $base > $TEMP_SVG  
    inkscape -e $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_100.png" -C -h $height $TEMP_SVG
    optipng $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_100.png"


    TARGET_PATH="m $svg_from  149.04109,0 c 2.88064,0 5.19971,2.31906 5.19971,5.1997 l 0,54.37882 c 0,2.88064 -2.31907,5.1997 -5.19971,5.1997 l -149.04109,0 c -2.88064,0 -5.19971,-2.31906 -5.19971,-5.1997 l 0,-16.72616 -11.56138,-10.46325 11.56138,-10.46325 0,-16.72616 c 0,-2.88064 2.31907,-5.1997 5.19971,-5.1997 z"
    xmlstarlet ed  -N "svg=http://www.w3.org/2000/svg" -u "//svg:svg/svg:g/svg:path[@id='progress']/@d" -v "$TARGET_PATH" $base > $TEMP_SVG
    xmlstarlet ed -L -N "svg=http://www.w3.org/2000/svg" -u "//svg:svg/svg:g/svg:path[@id='progress']/@style" -v "fill:#b2f494;fill-opacity:1;fill-rule:evenodd;stroke:none" $TEMP_SVG    
    inkscape -e $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_success.png" -C -h $height $TEMP_SVG
    optipng $OUTPUT_DIR_PREFIX"commons/api/button_${lenght}_${type}_success.png"

}

generateButtons "button_short_base.svg" "short" 20 "small" "347.26497,499.97307"
generateButtons "button_short_base.svg" "short" 26 "medium" "347.26497,499.97307"
generateButtons "button_short_base.svg" "short" 34 "big" "347.26497,499.97307"

generateButtons "button_long_base.svg" "long" 20 "small"    "402.40789,614.25878"
generateButtons "button_long_base.svg" "long" 26 "medium"    "402.40789,614.25878"
generateButtons "button_long_base.svg" "long" 34 "big"    "402.40789,614.25878"
