#!/bin/bash

function lessToCss {
	less=$1
    	echo Generate CSS for \'$less\'
	/var/lib/gems/1.8/bin/lessc $less www/resources/css/$(basename $less .less).css
	echo Finished to generate CSS for \'$less\'
}



mkdir -p www/resources/css/
for less in css/*.less ; do
	lessToCss $less &
done
