#!/bin/sh

OUTPUT_DIR_PREFIX=www_src/resources/
OUTPUT_DIR_SUFFIX=/img/
STAMP_OUTPUT_WIDTH=100

LANG_LIST="en fr"
STAMP_LIST="stamp_success stamp_failed"

generateRessources() {
    for LANG in $LANG_LIST ; do
        OUTPUT_FILE=$OUTPUT_DIR_PREFIX$LANG$OUTPUT_DIR_SUFFIX$1.png

        mkdir -p $(dirname $OUTPUT_FILE)
        inkscape -e $OUTPUT_FILE -C -w $2 sources/$1"_"$LANG.svg
        optipng $OUTPUT_FILE
    done
}

for STAMP in $STAMP_LIST ; do
    generateRessources $STAMP $STAMP_OUTPUT_WIDTH
done

generateRessources process_doc 800
generateRessources archi_doc 400

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/idea.png" -C -w 40 sources/idea.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/idea.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/team.png" -C -w 40 sources/team.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/team.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/message.png" -C -w 40 sources/message.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/message.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/withdraw_money.png" -C -w 40 sources/withdraw_money.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/withdraw_money.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/charge_account.png" -C -w 40 sources/charge_account.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/charge_account.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/logo_elveos.png" -C -w 150 sources/logo_elveos_beta.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/logo_elveos.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/favicon.png" -C -w 32 sources/favicon.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/favicon.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/idea_tiny.png" -C -h 20 sources/idea_tiny.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/idea_tiny.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/bug_tiny.png" -C -h 20 sources/bug_tiny.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/bug_tiny.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/comment_tiny.png" -C -h 20 sources/comment_tiny.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/comment_tiny.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/coins_tiny.png" -C -h 20 sources/coins_tiny.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/coins_tiny.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/offer_tiny.png" -C -h 20 sources/offer_tiny.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/offer_tiny.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/release_tiny.png" -C -h 20 sources/release_tiny.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/release_tiny.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/idea_small.png" -C -h 24 sources/idea_small.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/idea_small.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/settings_small.png" -C -h 24 sources/settings_small.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/settings_small.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/mail_settings_small.png" -C -h 24 sources/mail_settings_small.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/mail_settings_small.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/rss_small.png" -C -h 24 sources/rss_small.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/rss_small.png"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/mail_light.png" -C -h 12 sources/mail_light.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/mail_light.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/mail_dark.png" -C -h 12 sources/mail_dark.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/mail_dark.png"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/unfollow.png" -C -h 10 sources/unfollow.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/unfollow.png"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
