#!/bin/sh

OUTPUT_DIR_PREFIX=../www/resources/
OUTPUT_DIR_SUFFIX=/img/
STAMP_OUTPUT_WIDTH=100

LANG_LIST="en fr"
STAMP_LIST="stamp_success stamp_failed"

for STAMP in $STAMP_LIST ; do



    for LANG in $LANG_LIST ; do
        OUTPUT_FILE=$OUTPUT_DIR_PREFIX$LANG$OUTPUT_DIR_SUFFIX$STAMP.png

        mkdir -p $(dirname $OUTPUT_FILE)
        inkscape -e $OUTPUT_FILE -C -w $STAMP_OUTPUT_WIDTH $STAMP"_"$LANG.svg
        optipng $OUTPUT_FILE
    done
done


inkscape -e $OUTPUT_DIR_PREFIX"commons/img/idea.png" -C -w 40 idea.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/idea.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/team.png" -C -w 40 team.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/team.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/message.png" -C -w 40 message.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/message.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/withdraw_money.png" -C -w 40 withdraw_money.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/withdraw_money.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/charge_account.png" -C -w 40 charge_account.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/charge_account.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/logo_elveos.png" -C -w 150 logo_elveos_beta.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/logo_elveos.png"

inkscape -e $OUTPUT_DIR_PREFIX"commons/img/favicon.png" -C -w 32 favicon.svg
optipng $OUTPUT_DIR_PREFIX"commons/img/favicon.png"
